#!/bin/bash
read -p "Enter length: " l
read -p "Enter breadth: " b
rectArea=$(bc <<< "$l * $b")
rectPeri=$(bc <<< "2 *($l +$b)")
echo "Area of RECTANGLE: $rectArea"
echo "Perimeter of RECTANGLE: $rectPeri"
read -p "Enter the radius: " r
areaCircle=$(bc <<< "3.14 * $r * $r")
periCircle=$(bc <<< "2 * 3.14 * $r")
echo "Perimeter of CIRCLE: $periCircle"
echo "area of CIRCLE: $areaCircle"
