#!/bin/bash
if [ $# -eq 0 ]; then
        year=$(date +%Y)
else
        year=$1
fi

if (((year%100!=0&&year%4==0)||year%400==0)); then
        echo "$year is a Leap year"
else
        echo "$year is not a leap year"
fi

